# Generated by Django 2.0.2 on 2018-03-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.FloatField(default=432.32),
            preserve_default=False,
        ),
    ]
