# Generated by Django 2.0.2 on 2018-03-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_vehicle_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.ManyToManyField(to='new_app.Element')),
                ('vehicles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.Vehicle')),
            ],
        ),
    ]
