# Generated by Django 2.0.2 on 2018-03-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='vehicles',
            new_name='vehicle',
        ),
    ]
