# Generated by Django 2.0.2 on 2018-03-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_auto_20180322_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
