# Generated by Django 2.0.2 on 2018-03-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_element_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='weight_left',
            field=models.FloatField(null=True),
        ),
    ]
